// Generated by Typewriter Visual Studio Extension
${ 
    using Typewriter.Extensions.Types; 
    Template(Settings settings) { settings.OutputExtension = ".cs.d.ts"; }
}
declare module Server {
    $Classes([DataContract])[
    class $Name {
        $Properties[$name: $Type;
        ]
    }]
}